### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by coderschoolreview** [namviet3210/tips#1]
Many thanks, @namviet3210 for your submission. We will review and get back to you this week.

**Comment by minhchau273** [comment]
👍 Congratulation on finishing the Tip Calculator. Your app looks good.

#### Some small comments:
- Good usage of the `NSUserDefault`. This is one of the methods to pass data between view controllers.
- Your `,` doesn't work well. Can you check it again?  One more thing, it should be `.` instead of `,`.
  <img width="311" alt="screen shot 2016-06-23 at 10 10 36 pm" src="https://cloud.githubusercontent.com/assets/12395213/16308679/2b2c493a-3990-11e6-9f96-ddcf3951678a.png">
- You shouldn't let the user enter invalid number, should you? I can enter bunch of leading zeros and many dots. I can also paste some text in the text field:  
  <img width="301" alt="screen shot 2016-06-23 at 10 11 58 pm" src="https://cloud.githubusercontent.com/assets/12395213/16308739/663716ae-3990-11e6-917e-de8bebadb598.png">
- I really enjoy your emoji. They're so cute (^_^).
- Try to challenge yourself on the visual side to make your app more impressive 😉

**Comment by namviet3210** [comment]
Thank you minhchau273 for your comment.
- The decimal mark issue happens when user changes iPhone setting to use Vietnamese in Region format (Setting -> General -> Language and Regions -> Advanced -> Languages -> Vietnamese), where it uses "," instead of normal ".".
- The app will work normally if these setting to regions which use normal decimal mark "."
- I have updated in ver1 branch the feature to check user input, to make sure that only numbers and decimal mark "." are allows. 
- The instruction on Animation part is not clear to me, so I still defer that optional part.
  (ie. In order to animate one or more views, simply create an animation block.  <== it's not simply when I even't don't know what is animation block)

Cheers,
K

**Comment by namviet3210** [comment]
Thank you minhchau273 for your comment.

   - The decimal mark issue happens when user changes iPhone setting to use
   Vietnamese in Region format (Setting -> General -> Language and Regions ->
   Advanced -> Languages -> Vietnamese), where it uses "," instead of normal
   ".".
   - The app will work normally if these setting to regions which use
   normal decimal mark "."
   - I have updated in ver1 branch the feature to check user input, to make
   sure that only numbers and decimal mark "." are allows.
   - The instruction on Animation part is not clear to me, so I still defer
   that optional part. (ie. In order to animate one or more views, simply
   create an animation block. <== it's not simply when I even't don't know
   what is animation block)

Please check out my update version:
https://github.com/namviet3210/tips/tree/ver1.0

Cheers,
K

**Comment by minhchau273** [comment]
Thanks for your update. Everything looks good now 👍
